name: Publish to PyPI

on:
  push:
    tags:
      - 'v-*'
    branches:
      - main

jobs:
  pypi-publish:
    name: Upload to PyPI
    runs-on: ubuntu-latest
    environment:
      name: release
    permissions:
      id-token: write
    steps:
      - name: Install uv
        uses: astral-sh/setup-uv@v4

      - name: Set up Python
        run: uv python install 3.12

      - name: Build Wheels
        run: uv build

      - name: Publish to PyPi
        run: uv publish -v wheels/*
